### ISSUE TITLE
Forgot password not working

### ISSUE THREAD

**Issue by Sourabh782** [ANSHIKA-26/WordWise#853] opened 2024-10-12 17:05 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**
I wanted to make forgot password functionality implementable, using otp based verification.
When user clicks on forgot password, he will have to submit an email and OTP will be shared on mail, verifying OTP will allow user to reset password

**Screenshots**

**Additional context**

**Comment by Sourabh782** [comment] 2024-10-12 17:09
@ANSHIKA-26 can you check this issue? I can't find this issue in open and closed ones, also I have tested forgot password functionality, and it's not working, so can u open this issue?

**Comment by PulkitShubham** [comment] 2024-10-14 19:36
@ANSHIKA-26 Maam Please assign this task to me........I see the issue is still unresolved

**Comment by Sourabh782** [comment] 2024-10-15 01:19
@PulkitShubham it's only been 2 days + I have completed half work, and will make pr today

**Closed** 2024-10-16 15:36 UTC
Labels: gssoc-ext, level 2, hacktoberfest-accepted
