### ISSUE TITLE
their are some issues on about page 

### ISSUE THREAD

**Issue by anilgadhe** [ANSHIKA-26/WordWise#504] opened 2024-10-07 14:07 UTC
like imgs covers text at the time of hover @sanjay-kv

**Comment by Hemraj-7** [comment] 2024-10-07 14:26
I want to do this work

**Comment by Hemraj-7** [comment] 2024-10-07 14:30
![Screenshot 2024-10-07 195918](https://github.com/user-attachments/assets/6b2e1ef6-2b3d-4331-8cf4-5b2f0b9c1a3c)

**Comment by ANSHIKA-26** [comment] 2024-10-07 15:11
its first come first serve basis

**Comment by vijaychandra1910** [comment] 2024-10-07 17:28
@ANSHIKA-26 please assign it to me.

**Comment by lakshmirajvagu** [comment] 2024-10-08 08:31
please assign me this issue

**Comment by Hemraj-7** [comment] 2024-10-08 09:02
> its first come first serve basis

the issue is solved @ANSHIKA-26 merge pull request

**Closed** 2024-10-08 13:40 UTC
Labels: gssoc-ext, level 1, hacktoberfest-accepted
